Issue6: Confirmation pages
hack4impact-calpoly/lumina pull request #29
Opened 2022-02-25 00:43 UTC by thebarrettlo

Closes #6. Separated password change confirmation and new account creation confirmation pages into separate pages. Passing form data from the new account creation to the confirmation page took lots of time, but it now works using a react-router `<Navigate state={} />` and react-router `const location = useLocation();` on the receiving end.

2022-03-02 02:16 UTC, VincentPheng requested changes

2022-03-02 02:16 UTC, VincentPheng commented on frontend/src/components/ChangePasswordPage/ForgotPassword_Email.js
> +               <Box textAlign="center">
Remove box and center component

2022-03-02 02:16 UTC, VincentPheng commented on frontend/src/components/ChangePasswordPage/ForgotPassword_Email.js
> +        <CenterBox>
include textAlign="center" on centerbox again

2022-03-04 02:01 UTC, VincentPheng commented
Fix conflicts

2022-04-07 06:09 UTC, thebarrettlo commented
Bad commit history. See #38 for a working PR of issue 6.

2022-04-07 06:09 UTC, closed without merging